-- 预置国家队（onboarding 选主队用）。cron 会按需补充/匹配 the-odds-api 出现的球队。
-- 可重复运行：按 lower(name_en) 去重。

insert into public.teams (name_zh, name_en, flag_emoji) values
  ('美国', 'USA', '🇺🇸'),
  ('加拿大', 'Canada', '🇨🇦'),
  ('墨西哥', 'Mexico', '🇲🇽'),
  ('阿根廷', 'Argentina', '🇦🇷'),
  ('巴西', 'Brazil', '🇧🇷'),
  ('乌拉圭', 'Uruguay', '🇺🇾'),
  ('哥伦比亚', 'Colombia', '🇨🇴'),
  ('厄瓜多尔', 'Ecuador', '🇪🇨'),
  ('巴拉圭', 'Paraguay', '🇵🇾'),
  ('秘鲁', 'Peru', '🇵🇪'),
  ('智利', 'Chile', '🇨🇱'),
  ('法国', 'France', '🇫🇷'),
  ('英格兰', 'England', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('西班牙', 'Spain', '🇪🇸'),
  ('葡萄牙', 'Portugal', '🇵🇹'),
  ('德国', 'Germany', '🇩🇪'),
  ('荷兰', 'Netherlands', '🇳🇱'),
  ('意大利', 'Italy', '🇮🇹'),
  ('比利时', 'Belgium', '🇧🇪'),
  ('克罗地亚', 'Croatia', '🇭🇷'),
  ('瑞士', 'Switzerland', '🇨🇭'),
  ('丹麦', 'Denmark', '🇩🇰'),
  ('波兰', 'Poland', '🇵🇱'),
  ('塞尔维亚', 'Serbia', '🇷🇸'),
  ('奥地利', 'Austria', '🇦🇹'),
  ('捷克', 'Czech Republic', '🇨🇿'),
  ('土耳其', 'Turkey', '🇹🇷'),
  ('乌克兰', 'Ukraine', '🇺🇦'),
  ('苏格兰', 'Scotland', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  ('威尔士', 'Wales', '🏴󠁧󠁢󠁷󠁬󠁳󠁿'),
  ('挪威', 'Norway', '🇳🇴'),
  ('瑞典', 'Sweden', '🇸🇪'),
  ('希腊', 'Greece', '🇬🇷'),
  ('摩洛哥', 'Morocco', '🇲🇦'),
  ('塞内加尔', 'Senegal', '🇸🇳'),
  ('加纳', 'Ghana', '🇬🇭'),
  ('尼日利亚', 'Nigeria', '🇳🇬'),
  ('埃及', 'Egypt', '🇪🇬'),
  ('喀麦隆', 'Cameroon', '🇨🇲'),
  ('科特迪瓦', 'Ivory Coast', '🇨🇮'),
  ('突尼斯', 'Tunisia', '🇹🇳'),
  ('阿尔及利亚', 'Algeria', '🇩🇿'),
  ('马里', 'Mali', '🇲🇱'),
  ('南非', 'South Africa', '🇿🇦'),
  ('日本', 'Japan', '🇯🇵'),
  ('韩国', 'South Korea', '🇰🇷'),
  ('伊朗', 'Iran', '🇮🇷'),
  ('沙特阿拉伯', 'Saudi Arabia', '🇸🇦'),
  ('卡塔尔', 'Qatar', '🇶🇦'),
  ('澳大利亚', 'Australia', '🇦🇺'),
  ('新西兰', 'New Zealand', '🇳🇿'),
  ('乌兹别克斯坦', 'Uzbekistan', '🇺🇿'),
  ('约旦', 'Jordan', '🇯🇴'),
  ('伊拉克', 'Iraq', '🇮🇶'),
  ('哥斯达黎加', 'Costa Rica', '🇨🇷'),
  ('巴拿马', 'Panama', '🇵🇦'),
  ('洪都拉斯', 'Honduras', '🇭🇳'),
  ('牙买加', 'Jamaica', '🇯🇲')
on conflict (lower(name_en)) do nothing;
